---
title: "Build a blog"
date: 2023-06-22T13:32:14+08:00
draft: false
tags: ["hugo" "blog"]
categories: ["cs"]
---
* How to build your own blog?
I wanna build my own blog for a long time. Long ago, I have heard about Hugo, which is a convenient tool to build a static website quickly.

Following the [[https://www.youtube.com/watch?v=hjD9jTi_DQ4&list=PLeiDFxcsdhUrzkK5Jg9IZyiTsIMvXxKZP&index=2][course]] of Youtube, I have probably finished it today, and take a record for it now.
** Install Hugo
Easy for macos. Make sure that you have installed brew.

#+begin_src bash
  brew install hugo
#+end_src

** Create local website
Be familiar with the commands of Hugo.

#+begin_src bash
  hugo new site GrantSite
#+end_src

Now you can open VSCode or Emacs to edit your own blogs. Use

#+begin_src bash
  hugo server
#+end_src
to preview your website.

By the way, you can use Git to download a theme you like.

#+begin_src bash
  git init
  git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1
  git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
#+end_src

You also need to set your theme in your hugo.yml like this.

#+begin_src
  theme: PaperMod
#+end_src

** Upload your website
You need to configure github actions to publish the website to github pages. Before that, you should create a repository and upload it first.

#+begin_src bash
  git add README.md
  git commit -m "init the website"
  git branch -M main 
  git remote add origin git@github.com:Grant-S-Z/GrantSite.git
  git push -u origin main
#+end_src

After creating it, to make github do the jobs automatically, you need to establish the workflow. First of all, you should go to the repo actions and change the workflow permissions into "Read and write permissions". Then, add a .github/workflows/deploy.yml file under the project root directory like this.

#+begin_src 
name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo          
      - name: Build
        run: ${RUNNER_TEMP}/hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'dhij'
          git config user.email 'davidhwang.ij@gmail.com'
          git commit -m 'Updated site'
          git push    
#+end_src

After that, you can see your website. For me, here's [[https://grant-s-z.github.io/GrantSite/][it]].
